# Generated by Django 2.2 on 2020-10-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vidata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('publishedAt', models.CharField(blank=True, max_length=30, null=True)),
                ('channeltitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
