# Generated by Django 2.2 on 2020-10-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidata',
            name='thumbnail_medium',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
